"use strict"

export const nameList = 
[
    {
        title:"title1Feasibility and Usefulness of Out-of Office Cuffless Blood…",
        name:"naame1",
        img:[{
            url1:"../assets/header.svg"
        }]
    },
    {
        title:"title2",
        name:"naame2",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title3",
        name:"naame3",
        img:[{
      url1:"https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d745132d3.jpeg"
        },{
            url2:"https://img.freepik.com/premium-psd/falling-slice-ripe-red-apple-for-your-design_34168-1790.jpg?w=740"
        },{url3:"https://img.freepik.com/premium-psd/fresh-peach-with-leaves-isolated_328278-245.jpg?w=740"}
    ]
    },
    {
        title:"title4",
        name:"naame4",
        img:[{
            url1:"https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d745132d3.jpeg"
              },{
                  url2:"http://photos1.blogger.com/blogger/2921/1916/1600/photoshop_apples.jpg"
              },
{url3:"https://img.freepik.com/premium-psd/flat-design-korean-restaurant-poster-template_23-2150015831.jpg"}
          ]
    },
    {
        title:"title5",
        name:"naame5",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title6",
        name:"naame6",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title7",
        name:"naame7",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title8",
        name:"naame8",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title9",
        name:"naame9",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title10",
        name:"naame10",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title11",
        name:"naame11",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title12",
        name:"naame12",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title13",
        name:"naame13",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title14",
        name:"naame14",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title15",
        name:"naame15",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title16",
        name:"naame16",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title17",
        name:"naame17",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title18",
        name:"naame18",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title19",
        name:"naame19",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title20",
        name:"naame20",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title21",
        name:"naaame21",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title22",
        name:"naame22",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title23",
        name:"naame23",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title24",
        name:"name24",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title25",
        name:"name25",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title26",
        name:"name26",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title27",
        name:"name27",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title28",
        name:"name28",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title29",
        name:"name29",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title30",
        name:"name30",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title31",
        name:"name31",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title32",
        name:"name32",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title33",
        name:"name33",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title34",
        name:"name34",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title35",
        name:"name35",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title36",
        name:"name36",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title37",
        name:"name37",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title38",
        name:"name38",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title39",
        name:"name39",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title40",
        name:"name40",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title41",
        name:"name41",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title42",
        name:"name42",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title43",
        name:"name43",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title44",
        name:"name44",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title45",
        name:"name45",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title46",
        name:"name46",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title47",
        name:"name47",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title48",
        name:"name48",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title49",
        name:"name49",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title50",
        name:"name50",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title51",
        name:"name51",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title52",
        name:"name52",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title53",
        name:"name53",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title54",
        name:"name54",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title55",
        name:"name55",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title56",
        name:"name56",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title57",
        name:"name57",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title58",
        name:"name58",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title59",
        name:"name59",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title60",
        name:"name60",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },   {
        title:"title61",
        name:"name61",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title62",
        name:"name62",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title63",
        name:"name63",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title64",
        name:"name64",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title65",
        name:"name65",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title66",
        name:"name66",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title67",
        name:"name67",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title68",
        name:"name68",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title69",
        name:"name69",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title70",
        name:"name70",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title71",
        name:"name71",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title72",
        name:"name72",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title73",
        name:"name73",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title74",
        name:"name74",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title75",
        name:"name75",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title76",
        name:"name76",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title77",
        name:"name77",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title78",
        name:"name78",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title79",
        name:"name79",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
    {
        title:"title80",
        name:"name80",
        img:[{
            url1:"./assets/bg.png"
        },{
            url2:"./assets/bg.png"
        }]
    },
]
